### ISSUE TITLE
where can I get this paper? Thanks

### ISSUE THREAD

**Issue by Ai-is-light** [zhanglijun95/FIIQA#1]
where can I get this paper? Thanks

**Comment by zhanglijun95** [comment]
Sorry, this paper is still under review.

**Comment by YongboYu** [comment]
Really？I remembered that you said this paper was submitted to ICONIP ? Did the ICONIP say when your paper will be accepted？

**Comment by zhanglijun95** [comment]
Hello. The paper has been published in ICONIP. The link is https://link.springer.com/chapter/10.1007%2F978-3-319-70090-8_59.
