### ISSUE TITLE
PatternScores in repo does not match PatternScores in dataset

### ISSUE THREAD

**Issue by ebeyabraham** [zhanglijun95/FIIQA#11]
Hi, thank you for sharing the code and dataset for your paper. I had a doubt regarding the pattern scores given in the illumination patterns dataset (`patternsScores.mat`). From what I understand from the paper, these values are the subjective scores after normalisation. These are not in the range [0,1]. However, the pattern scores in the github repo (`pScores.mat`) are in the range [0,1]. 

Also, patterns with ranks 0 and 193 seem to have the same score, which is a bit confusing as they are supposed to be at the two extremes. Could you give a bit more detail on how these scores are used, in case I am misunderstanding them? Thanks!

**Comment by zhanglijun95** [comment]
Please use the score files in the repo `newScores/`. The score for rank 0 is 0, while that for rank 193 is 1 as shown in `pScores.mat`.
