### ISSUE TITLE
Same patterns having diffreent quality labels

### ISSUE THREAD

**Issue by ParnianA** [zhanglijun95/FIIQA#12]
Hi,

Why faces with the same illumination pattern (like cafe-inside-1) have different quality labels?

Thanks,
Parnian

**Comment by zhanglijun95** [comment]
Are you using the new score file in the repo folder `newScores/`? This situation won't happen because all the images in `*.txt` are labeled by the pattern, e.g., cafe-inside-1 is 102. Then the same pattern has one score in `pScore.mat`
