### ISSUE TITLE
License for dataset and the model

### ISSUE THREAD

**Issue by RomanKiryanov** [zhanglijun95/FIIQA#13]
Hello,
Thanks for the great work. I tried to find the information about the usage of the datasets and the model for commercial purposes, but I did not find any mentioned license or any information in your paper (https://cslinzhang.gitee.io/home/files/ICONIP_FIIQA.pdf). Can you please add license information for the dataset and the model?

Thanks a lot.

**Comment by zhanglijun95** [comment]
The license has been created. Thanks.

**Comment by RomanKiryanov** [comment]
Awesome! Thanks for the update. Great work!
