### ISSUE TITLE
What is the meaning of label in test_standard?

### ISSUE THREAD

**Issue by xtj49** [zhanglijun95/FIIQA#2]
As the paper said, "For the images whose illumination patterns are transferred from Ri, their illumination quality scores are assigned as si". The quality label should be in the range of [0,199]. But the range of label in the test_standard is [0,2]. I can't figure out why. can you help me?

**Comment by zhanglijun95** [comment]
Thank you for your attention. 
Your question does exist. I have uploaded the correct document in the test-real/ folder.

**Comment by zhanglijun95** [comment]
> > Thank you for your attention.
> > Your question does exist. I have uploaded the correct document in the test-real/ folder.
> 
> The val_standard.txt and train_standard.txt are also wrong. Maybe it's time to update a new txt version.

Yes. The new ones are in newScores/ now.

**Comment by xtj49** [comment]
How to explain in the file "patternsRank" and "patternsNames", the rank of "KFC-window-2pm-1.JPG" is 58. But in new score file, the rank of "KFC-window-2pm-1.JPG" is 67. Which one should I choose?

**Comment by zhanglijun95** [comment]
> How to explain in the file "patternsRank" and "patternsNames", the rank of "KFC-window-2pm-1.JPG" is 58. But in new score file, the rank of "KFC-window-2pm-1.JPG" is 67. Which one should I choose?

Use the new one.
Actually, the old one is calculated from just one person, while the new one is from more evaluators. So there exists difference.

**Comment by xtj49** [comment]
> > How to explain in the file "patternsRank" and "patternsNames", the rank of "KFC-window-2pm-1.JPG" is 58. But in new score file, the rank of "KFC-window-2pm-1.JPG" is 67. Which one should I choose?
> 
> Use the new one.
> Actually, the old one is calculated from just one person, while the new one is from more evaluators. So there exists difference.

Okey, I know. Thank you for your patience and contribution!

**Comment by xtj49** [comment]
> > How to explain in the file "patternsRank" and "patternsNames", the rank of "KFC-window-2pm-1.JPG" is 58. But in new score file, the rank of "KFC-window-2pm-1.JPG" is 67. Which one should I choose?
> 
> Use the new one.
> Actually, the old one is calculated from just one person, while the new one is from more evaluators. So there exists difference.

And where is the new scores?

**Comment by gdjmck** [comment]
Are the annotation files currently in the Baidu cloud disk the updated version? Or anywhere I can just download the annotation file alone?

**Comment by zhanglijun95** [comment]
Hello there,
You should download the annotation file in Github alone.



 
---Original---
