### ISSUE TITLE
caffe source code

### ISSUE THREAD

**Issue by yangyuke001** [zhanglijun95/FIIQA#3]
作者你好，首先感谢分享！
我最近在搞人脸光照质量评价相关的项目，看到你的这个方法，
请问方便提供一下caffe训练resnet50的源码么？邮箱：1328069190@qq.com
论文没有相关的实现细节，不好复现，再次感谢！

**Comment by zhanglijun95** [comment]
你好！
这篇文章caffe框架就用的官方的，resnet50的网络架构文件也是原作者提供的，并没有对它们做任何改动。

**Comment by zhanglijun95** [comment]
> 作者你好，首先感谢分享！
> 我最近在搞人脸光照质量评价相关的项目，看到你的这个方法，
> 请问方便提供一下caffe训练resnet50的源码么？邮箱：[1328069190@qq.com](mailto:1328069190@qq.com)
> 论文没有相关的实现细节，不好复现，再次感谢！
你好！
这篇文章caffe框架就用的官方的，resnet50的网络架构文件也是原作者提供的，并没有对它们做任何改动。

**Comment by zhanglijun95** [comment]
> 作者你好，首先感谢分享！
> 我最近在搞人脸光照质量评价相关的项目，看到你的这个方法，
> 请问方便提供一下caffe训练resnet50的源码么？邮箱：[1328069190@qq.com](mailto:1328069190@qq.com)
> 论文没有相关的实现细节，不好复现，再次感谢！

你好！
这篇文章caffe框架就用的官方的，resnet50的网络架构文件也是原作者提供的，并没有对它们做任何改动。

**Comment by yangyuke001** [comment]
@zhanglijun95 多谢回复。这几天费老劲也没装好matcaffe接口，我在看要不要换成pytorch框架去复现。

**Comment by yangyuke001** [comment]
另外，我对每个图片给定的评分（0-200），例如是1.jpg 158，那么这个得分158是怎么映射到（0，1）呢？具体的计算方法paper里没太搞懂，还望作者不吝赐教，感谢！

**Comment by zhanglijun95** [comment]
实现：用什么框架都可以，tensorflow,pytorch都可以
评分：文中有说到，每一个reference图像都有一个关于光照水平的评分，这个评分是通过人工评分得到的0-1分数，那么数据集中每张从同一个reference图像得到的图像分数都是一样的这个分数。


 
---Original---

**Comment by yangyuke001** [comment]
@zhanglijun95 了然咯
