### ISSUE TITLE
光照迁移模型

### ISSUE THREAD

**Issue by Dreamgang** [zhanglijun95/FIIQA#5]
您好，请问论文中提到的光照迁移模型，从哪里可以下载到源码，方便的话，您可以发我一份吗？249054793@qq.com。谢谢您！

**Comment by zhanglijun95** [comment]
你好，光照迁移模型是论文中提到的别人论文里的方法，代码是我们自己实现的，你也可以考虑自己实现。


 
---原始邮件---
发件人: "Dreamgang"<notifications@github.com>
发送时间: 2019年7月15日(星期一) 晚上8:38
收件人: "zhanglijun95/FIIQA"<FIIQA@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zhanglijun95/FIIQA] 光照迁移模型 (#5)



您好，请问论文中提到的光照迁移模型，从哪里可以下载到源码，方便的话，您可以发我一份吗？249054793@qq.com。谢谢您！

**Comment by Dreamgang** [comment]
@zhanglijun95 您好，请问您是根据什么条件来构建illumination patterns的，我看了一下这里面的图片，0~199，分数越大，图片质量越高，但是我看了里面有些分数大的图片，比分数低的图片，光照还要暗。所以想问下你们是依据什么来给这些图片打分的，谢谢

**Comment by zhanglijun95** [comment]
你好。拍摄条件是多种场景多种角度排列组合，评分原则是找多名志愿者做主观评分后，去离群值取平均得到的。这些在论文里有说明。


 
---原始邮件---
发件人: "Dreamgang"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 上午10:50
收件人: "zhanglijun95/FIIQA"<FIIQA@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"Ivy Zhang"<670725540@qq.com>;
主题: Re: [zhanglijun95/FIIQA] 光照迁移模型 (#5)



@zhanglijun95 您好，请问您是根据什么条件来构建illumination patterns的，我看了一下这里面的图片，0~199，分数越大，图片质量越高，但是我看了里面有些分数大的图片，比分数低的图片，光照还要暗。所以想问下你们是依据什么来给这些图片打分的，谢谢

**Comment by Dreamgang** [comment]
好的，我去阅读一下论文，谢谢您!
