### ISSUE TITLE
The shared links to the dataset are cancelled?

### ISSUE THREAD

**Issue by HSE-asavchenko** [zhanglijun95/FIIQA#6]
I'm trying to download your dataset (train/val) but Baidu disk reports that the shared files are canceled. Is it still available?
Thanks

**Comment by AngeloUNIMI** [comment]
Same for me, is there the possibility to obtain them in another way?
thank you very much

**Comment by HSE-asavchenko** [comment]
I just tried to test the download once more and it works! I confirm that all the links works fine right now.

**Comment by AngeloUNIMI** [comment]
Could you please make this link available in some other online storage? I cannot seem to download it in any way.

Face Illumination Quality Assessment Model: FIIQADCNN
http://pan.baidu.com/s/1jIHr7t8

thanks a lot,

**Comment by HSE-asavchenko** [comment]
Yes, sure. Here it is
https://drive.google.com/open?id=14wTY4MbLtBQqcudCq97pLTLRnYMb1Rza
Please be aware that I will remove this link in a month due to the limited size of my google drive

**Comment by AngeloUNIMI** [comment]
thank you very much, I downloaded it

**Comment by HSE-asavchenko** [comment]
Good. I'm closing this issue

**Comment by vuars** [comment]
Can you share with me google drive data link or directly send it to me through my email address? vuars3101998@gmail.com.
Many thanks!!!
