### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by veriff-javiervgd** [zhanglijun95/FIIQA#9]
Hi! thank you for publishing this work in open-source. I was wondering if it could be possible to get an open link to the article? Very interesting research :)

**Comment by zhanglijun95** [comment]
Hi, thank you for your interest. [Here ](http://cslinzhang.gitee.io/home/files/ICONIP_FIIQA.pdf)is another link for you.

**Comment by veriff-javiervgd** [comment]
Thank you for the link. This work is a pioneer in factor-specific FIQA. Now most approaches focus on monolithic FIQA with a single quality score. But for the sake of explainability I do believe that each image factor (being one of the most critical the illumination) must be assessed separately for quality assessment. Congrats for the work!
